version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 4433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret1234
    volumes:
      - mssqldata:/var/opt/mssql
      - ./database/backup:/var/opt/mssql/backup
  server:
    build:
        context: ./
        dockerfile: ./Dockerfile
    image: jskonst/lecture_sample
    ports:
      - 5000:80
    depends_on:
      - "mssql"
    volumes:
      - "./Server v0.0/appsettings.Docker.json:/app/appsettings.json"

volumes:
  mssqldata:
    external: true